import ps0 

print("Test Cases:")
print("")
print("The number 6 is even: {}".format(ps0.isEven(6)))
print("The number 7 is even: {}".format(ps0.isEven(7)))
print("The number 50 is {} digits long".format(ps0.lengthofNumber(50)))
print("The number 100 is {} digits long".format(ps0.lengthofNumber(100)))
print("The sum of the digits in 123 is {}".format(ps0.sumDigits(123)))
print("The sum of the digits in 99 is {}".format(ps0.sumDigits(99)))
print("The sum of all the digits less than 10 is {}".format(ps0.lessthanGiven(10)))
print("The sum of all the digits less than 62 is {}".format(ps0.lessthanGiven(62)))
print("12! is {}".format(ps0.factorialFinder(12)))
print("6! is {}".format(ps0.factorialFinder(6)))
print("6 is a factor of 7: {}".format(ps0.isFactor(6,7)))
print("4 is a factor of 16: {}".format(ps0.isFactor(16,4)))
print("All the factors of 15 excluding itself are {}".format(ps0.allFactors(15)))
print("All the factors of 200 excluding itself are {}".format(ps0.allFactors(200)))
print("8 is prime: {}".format(ps0.isPrime(8)))
print("17 is prime: {}".format(ps0.isPrime(17)))
print("28 is perfect: {}".format(ps0.isPerfect(28)))
print("143 is perfect: {}".format(ps0.isPerfect(143)))
print("The sum of the digits in 12 divides evenly into 12: {}".format(ps0.divEven(12)))
print("The sum of the digits in 75 divides evenly into 75: {}".format(ps0.divEven(75)))
